# %%
import logging

logging.exception("Something wrong happened")
